#ifndef DHT22_DEFINES_H
#define DHT22_DEFINES_H

//
// Basic
//

#define DHT_READ_DATA_SIZE 4

#define DHT_SENSING_PERIOD_S 2

#define DHT_INTEGRAL_RH_DATA_OFFSET 0
#define DHT_DECIMAL_RH_DATA_OFFSET 1
#define DHT_INTEGRAL_T_DATA_OFFSET 2
#define DHT_DECIMAL_T_DATA_OFFSET 3

#endif // DHT22_DEFINES_H