#ifndef GLOBAL_CONSTS_H
#define GLOBAL_CONSTS_H

#define VITROIO_TEMPLATE_REGION_A_FLASH_OFFSET       0x10800
#define VITROIO_TEMPLATE_REGION_B_FLASH_OFFSET       0x88000
// Sectors sizes may differ for other targets
#define VITROIO_TEMPLATE_REGION_FLASH_SECTORS        239 // 74*2048=151552 (0x25000)

#define VITROIO_TEMPLATE_ENVIRONMENT_FLASH_OFFSET    0x10000
#define VITROIO_TEMPLATE_ENVIRONMENT_FLASH_SECTORS   1 // 1*2048=2048 (0x800)

#define VITROIO_TEMPLATE_VERSION_MAJOR   1
#define VITROIO_TEMPLATE_VERSION_MINOR   1
#define VITROIO_TEMPLATE_VERSION_PATCH   1
#define VITROIO_TEMPLATE_VERSION_RC      0

#define VITRIOIO_TEMPLATE_FIRMWARE_ID    0

#define VITROIO_TEMPLATE_STATUS_LED_PIN PA_5

#define TEMPLATE_DEBUG    0

#endif // GLOBAL_CONSTS_H
