#ifndef GLOBAL_CONSTS_H
#define GLOBAL_CONSTS_H

#define VITROIO_TEMPLATE_VERSION_MAJOR   1
#define VITROIO_TEMPLATE_VERSION_MINOR   2
#define VITROIO_TEMPLATE_VERSION_PATCH   0
#define VITROIO_TEMPLATE_VERSION_RC      0

#define VITRIOIO_TEMPLATE_FIRMWARE_ID    0

#define VITROIO_TEMPLATE_STATUS_LED_PIN PA_5

#define TEMPLATE_DEBUG    0

#endif // GLOBAL_CONSTS_H
