#ifndef GLOBAL_CONSTS_H
#define GLOBAL_CONSTS_H

#define VITROIO_DHT_DEMO_REGION_A_FLASH_OFFSET       0x10800
#define VITROIO_DHT_DEMO_REGION_B_FLASH_OFFSET       0x88000
// Sectors sizes may differ for other targets
#define VITROIO_DHT_DEMO_REGION_FLASH_SECTORS        239

#define VITROIO_DHT_DEMO_ENVIRONMENT_FLASH_OFFSET    0x10000
#define VITROIO_DHT_DEMO_ENVIRONMENT_FLASH_SECTORS   1 // 1*2048=2048 (0x800)

#define VITROIO_DHT_DEMO_VERSION_MAJOR   5
#define VITROIO_DHT_DEMO_VERSION_MINOR   1
#define VITROIO_DHT_DEMO_VERSION_PATCH   6
#define VITROIO_DHT_DEMO_VERSION_RC      0

#define VITRIOIO_DHT_DEMO_FIRMWARE_ID    0

#define VITROIO_DHT_DEMO_STATUS_LED_PIN PA_5

#define DHT_DEMO_DEBUG    0

#endif // GLOBAL_CONSTS_H
